services:
  dalpo-webapp:
    build:
      context: .
      dockerfile: WebApp.Dockerfile
    ports:
      - "8080:80"
    environment:
      # Load environment variables from .env file
      - AUTH_ENABLED=${AUTH_ENABLED:-false}
      - AUTH_CLIENT_SECRET=${AUTH_CLIENT_SECRET}
      - AZURE_COSMOSDB_ACCOUNT=${AZURE_COSMOSDB_ACCOUNT}
      - AZURE_COSMOSDB_ACCOUNT_KEY=${AZURE_COSMOSDB_ACCOUNT_KEY}
      - AZURE_COSMOSDB_CONVERSATIONS_CONTAINER=${AZURE_COSMOSDB_CONVERSATIONS_CONTAINER}
      - AZURE_COSMOSDB_DATABASE=${AZURE_COSMOSDB_DATABASE}
      - AZURE_OPENAI_ENDPOINT=${AZURE_OPENAI_ENDPOINT}
      - AZURE_OPENAI_KEY=${AZURE_OPENAI_KEY}
      - AZURE_OPENAI_MODEL=${AZURE_OPENAI_MODEL}
      - AZURE_OPENAI_MODEL_NAME=${AZURE_OPENAI_MODEL_NAME}
      - AZURE_OPENAI_RESOURCE=${AZURE_OPENAI_RESOURCE}
      - AZURE_OPENAI_MAX_TOKENS=${AZURE_OPENAI_MAX_TOKENS}
      - AZURE_OPENAI_TEMPERATURE=${AZURE_OPENAI_TEMPERATURE}
      - AZURE_OPENAI_TOP_P=${AZURE_OPENAI_TOP_P}
      - AZURE_OPENAI_STOP_SEQUENCE=${AZURE_OPENAI_STOP_SEQUENCE}
      - AZURE_OPENAI_SYSTEM_MESSAGE=${AZURE_OPENAI_SYSTEM_MESSAGE}
      - AZURE_OPENAI_EMBEDDING_ENDPOINT=${AZURE_OPENAI_EMBEDDING_ENDPOINT}
      - AZURE_OPENAI_EMBEDDING_KEY=${AZURE_OPENAI_EMBEDDING_KEY}
      - AZURE_OPENAI_EMBEDDING_NAME=${AZURE_OPENAI_EMBEDDING_NAME}
      - AZURE_SEARCH_SERVICE=${AZURE_SEARCH_SERVICE}
      - AZURE_SEARCH_INDEX=${AZURE_SEARCH_INDEX}
      - AZURE_SEARCH_KEY=${AZURE_SEARCH_KEY}
      - AZURE_SEARCH_CONTENT_COLUMNS=${AZURE_SEARCH_CONTENT_COLUMNS}
      - AZURE_SEARCH_FILENAME_COLUMN=${AZURE_SEARCH_FILENAME_COLUMN}
      - AZURE_SEARCH_TITLE_COLUMN=${AZURE_SEARCH_TITLE_COLUMN}
      - AZURE_SEARCH_URL_COLUMN=${AZURE_SEARCH_URL_COLUMN}
      - AZURE_SEARCH_VECTOR_COLUMNS=${AZURE_SEARCH_VECTOR_COLUMNS}
      - AZURE_SEARCH_QUERY_TYPE=${AZURE_SEARCH_QUERY_TYPE}
      - AZURE_SEARCH_USE_SEMANTIC_SEARCH=${AZURE_SEARCH_USE_SEMANTIC_SEARCH}
      - AZURE_SEARCH_SEMANTIC_SEARCH_CONFIG=${AZURE_SEARCH_SEMANTIC_SEARCH_CONFIG}
      - AZURE_SEARCH_TOP_K=${AZURE_SEARCH_TOP_K}
      - AZURE_SEARCH_ENABLE_IN_DOMAIN=${AZURE_SEARCH_ENABLE_IN_DOMAIN}
      - AZURE_SEARCH_STRICTNESS=${AZURE_SEARCH_STRICTNESS}
      - AZURE_SEARCH_PERMITTED_GROUPS_COLUMN=${AZURE_SEARCH_PERMITTED_GROUPS_COLUMN}
      - DATASOURCE_TYPE=${DATASOURCE_TYPE}
      # UI Configuration
      - UI_CHAT_LOGO=${UI_CHAT_LOGO}
      - UI_CHAT_DESCRIPTION=${UI_CHAT_DESCRIPTION}
      - UI_CHAT_TITLE=${UI_CHAT_TITLE}
      - UI_TITLE=${UI_TITLE}
      # Local development settings
      - ENVIRONMENT=${ENVIRONMENT:-development-local}
      - DEBUG=${DEBUG:-true}
    env_file:
      - .env
    volumes:
      # Mount source code for development (optional - comment out for production-like behavior)
      - ./app.py:/usr/src/app/app.py
      - ./backend:/usr/src/app/backend
    restart: unless-stopped
